# ~/.config/kitty/kitty.conf

# ----------------------------
# Environment
# ----------------------------
#term xterm-256color
term xterm-kitty

# ----------------------------
# Window
# ----------------------------
dynamic_title yes
hide_window_decorations yes
background_opacity 1

window_padding_width 8
placement_strategy top-left

# ----------------------------
# Scrolling
# ----------------------------
scrollback_lines 50000
wheel_scroll_multiplier 3.0

# ----------------------------
# Font
# ----------------------------
font_family      CaskaydiaCove Nerd Font
bold_font        CaskaydiaCove Nerd Font Bold
italic_font      CaskaydiaCove Nerd Font Italic
bold_italic_font auto
font_size 12.0

# ----------------------------
# Cursor
# ----------------------------
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
# cursor_text_color #1a1b26

# ----------------------------
# Mouse / Selection
# ----------------------------
mouse_hide_wait -1.0
copy_on_select clipboard

# ----------------------------
# Keyboard bindings
# Keep minimal so tmux/vim own the keyboard
# ----------------------------
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

map ctrl+shift+f show_scrollback
map ctrl+shift+b show_scrollback

map ctrl+equal     change_font_size all +1.0
map ctrl+plus      change_font_size all +1.0
map ctrl+minus     change_font_size all -1.0
map ctrl+0         change_font_size all 0

map ctrl+shift+n launch --type=os-window --cwd=current
# ----------------------------
# Colors
# ----------------------------


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
